FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

ENV CI=true

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install

EXPOSE 5173

CMD ["pnpm", "dev"]
